CREATE DATABASE DB_GOOGLE

USE DB_GOOGLE

CREATE TABLE TB_POSTS(
	ID	INT IDENTITY PRIMARY KEY NOT NULL,
	TITULO	VARCHAR(100) NOT NULL,
	AUTOR	VARCHAR(100) NOT NULL,
	CONTEUDO VARCHAR(MAX) NOT NULL
)

SELECT * FROM TB_POSTS

INSERT INTO TB_POSTS(TITULO, AUTOR, CONTEUDO) VALUES('CRÍTICA: RESIDENT EVIL 6','JOSÉ ANTUNES', 'É UM FILME MUITO LEGAL E DIVERTIDO INDICADO PARA TODA A FAMÍLIA')

SELECT * FROM TB_POSTS